### ISSUE TITLE
Do we really need `qemu-debootstrap`

### ISSUE THREAD

**Issue by marmistrz** [dderby/debian900#27]
It's not present in Arch Linux and this Stack post suggests simply symlinking it...

http://unix.stackexchange.com/questions/153691/no-qemu-debootstrap-in-arch-linux

Can we simply move to standard deboostrap?

**Comment by dderby** [comment]
qemu-debootstrap is a wrapper script which provides an architecture independent way to setup qemu syscall emulation in a debootstrap chroot.  It copies the qemu-arm-static executable to the debootstrap target which allows chroot to work with a foreign architecture.

Symlinking or copying the executable name, as suggested on your StackExchange link, will not work when working with a foreign architecture as we are doing here and it will also fail for LXC when working with foreign architectures.

Whilst it is possible to integrate qemu-deboostrap functionality into install_debian.sh, I'd prefer to keep it as lean as possible.  I will not change it as this functionality is available elsewhere.

I think correct solution would be to package qemu-deboostrap for Arch Linux given that it is also required to be able to run Debian-based foreign architecture LXC containers under Arch Linux.  You can obtain the qemu-deboostrap script from the Debian source package for qemu-user-static:

http://http.debian.net/debian/pool/main/q/qemu/qemu_2.6+dfsg-3.debian.tar.xz

**Comment by marmistrz** [comment]
In fact, the Arch's `debootstrap` combines Debian's `debootstrap` and `qemu-debootstrap`, see http://paste.ubuntu.com/19060930/
