### ISSUE TITLE
Arch uses `qemu-arm`

### ISSUE THREAD

**Issue by marmistrz** [dderby/debian900#29]
not `qemu-arm-static`.

We should add some configuration of the qemu executable

**Comment by dderby** [comment]
Debian also uses "qemu-arm", however "qemu-arm-static" is also provided.  The distinction is that qemu-arm-static is statically linked.  This is required to be able to chroot into a foreign architecture.  Please use a statically linked qemu executable.  If it one not available for Arch Linux you can try using the one from Debian:

https://packages.debian.org/sid/qemu-user-static

**Comment by dderby** [comment]
I happened to stumble onto this which might help you:

https://aur.archlinux.org/packages/qemu-user-static/

It looks like it comes from Debian so it may even include qemu-debootstrap.
